project:
  type: website
  output-dir: docs

website:
  title: "DSCI 522 Lab Slides"
  navbar:
    left:
      - text: "Lab 1"
        href: lab1-intro.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

